name: Publish to dev.to on Feature Branch

on:
  push:
    branches:
      - feature/**   # change this to match your feature branch naming

jobs:
  publish-to-devto:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Publish markdown posts to dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '_posts/**/*.md'   # your markdown post path
          branch: feature
